# Generated by Django 6.1 on 2026-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='included_not_included',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary_days',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
