# Generated by Django 6.1 on 2026-08-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tour_included_not_included_tour_itinerary_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
