# Generated by Django 6.1 on 2026-08-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_tour_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allotment', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='catalog.tour')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_infant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='inventory.touravailability')),
            ],
        ),
    ]
